services:
  - type: web
    name: calligraphy-analyzer
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: MPLBACKEND
        value: Agg
      - key: GEN_GENERATE_URL
        value: https://doreenlqy071--calli-gen-server-generate-endpoint.modal.run
      - key: GEN_HEALTH_URL
        value: https://doreenlqy071--calli-gen-server-health.modal.run
